Mega update
stefna/php-mailchimp-api-v3 pull request #1
Opened 2022-10-10 14:35 UTC by arnar-peturs

Run php stan to max level

2022-10-10 16:50 UTC, sunkan commented
@arnar-peturs 

Can you add the files needed for github actions?

You can copy the files from here https://github.com/stefna/islandis-auth/tree/master/.github/workflows

Just remove php7.1 - 7.3 from the matrixes

2022-10-11 12:24 UTC, arnar-peturs commented
@sunkan 
Did add the workflow things. You might want to take a look the failing checks

2022-10-25 12:59 UTC, sunkan requested changes

2022-10-25 12:59 UTC, sunkan commented on composer.json
> +    "stefna/release-tools": "^1.5"
Remove `stefna/release-tools` it's not a public package

2022-10-25 12:59 UTC, sunkan commented on tests/Api/Campaigns/ContentsTest.php
> +		$rp = new ReflectionProperty(Content::class, 'plainText');
Short answer too this is NO

I think the correct solution to this is to change ` Stefna\Mailchimp\Model\Campaign\Content`

from
```php
public string $plainText;
```
to
```php
public ?string $plainText = null;
```

And I think this is the solution for all places you get `must not be accessed before initialization` errors

2022-10-28 12:35 UTC, bix0r commented on src/Client.php
>  		$this->messageFactory = $messageFactory ?: MessageFactoryDiscovery::find();
@sunkan Shouldn't we try to switch this out for something that is not deprecated?

2022-10-28 12:36 UTC, bix0r commented
I think this is starting to look good :) 

Perhaps we should force the code-style in ci also?

2022-11-02 15:05 UTC, arnar-peturs commented
@sunkan @bix0r 
Ready for final review?

2022-11-02 16:32 UTC, sunkan requested changes

2022-11-02 16:32 UTC, sunkan commented on src/Client.php
>  		$this->messageFactory = $messageFactory ?: MessageFactoryDiscovery::find();
I think we should merge this then I can make a separate pr with that change

2022-11-02 16:32 UTC, sunkan commented on src/Client.php
> +	 * @return string[]
@arnar-peturs this type hint is wrong it should be `array<string, string>`

`string[]` means `array<int, string>`

2022-11-02 16:32 UTC, sunkan commented on src/Model/Campaign/ABTestOptions.php
> +	//public $contents;
If it's not in the api shouldn't it be removed?

2022-11-02 16:32 UTC, sunkan commented on src/Model/Campaign/CampaignList/SegmentOptions.php
> +	 * @var array<int|array<string, string>>
Did you mean `array<int, array<string, string>>`?

2022-11-22 09:50 UTC, sunkan approved these changes

2022-11-22 17:19 UTC, bix0r approved these changes
LGTM

2022-11-23 12:48 UTC, merged